### ISSUE TITLE
Investigate DEB_BUILD_PROFILES

### ISSUE THREAD

**Issue by mdavidsaver** [epicsdeb/epics-base#14]
With https://wiki.debian.org/BuildProfileSpec Debian supports conditional binary packages and build dependencies.  Lack of this is what led to the split of epics-base and rtems-epics as separate source packages.

**Comment by mdavidsaver** [comment]
With this feature it should be possible to do something like ```DEB_BUILD_PROFILES=rtems``` to conditionally enable building of RTEMS packages.

**Comment by mark0n** [comment]
I have modified the affected packages - see the following PRs:
* [asyn](https://github.com/epicsdeb/asyn/pull/5)
* [autosave](https://github.com/epicsdeb/autosave/pull/6)
* [busy](https://github.com/epicsdeb/busy/pull/1)
* [calc](https://github.com/epicsdeb/calc/pull/4)
* [caputlog](https://github.com/epicsdeb/caputlog/pull/13)
* [deviocstats](https://github.com/epicsdeb/deviocstats/pull/4)
* [devlib2](https://github.com/epicsdeb/devlib2/pull/16)
* [motor](https://github.com/epicsdeb/motor/pull/3)
* [mrfioc2](https://github.com/epicsdeb/mrfioc2/pull/2)
* [seq](https://github.com/epicsdeb/seq/pull/2)
* [sscan](https://github.com/epicsdeb/sscan/pull/2)
* [stream](https://github.com/epicsdeb/stream/pull/2)

**Comment by aderbenev** [comment]
I got all affected packages rebuilt with master/epics-master 3.15.5, and put it all on the test system. I want to assemble and test an RTEMS app with all modules now to see that all is good there.

**Comment by aderbenev** [comment]
All relevant module PRs should be merged now.

**Comment by mark0n** [comment]
@aderbenev, thanks a lot for testing!
